//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace AuthService
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputCreateSession", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputCreateSession : object
    {

        private AuthService.WebServiceInputCreateSessionParams ParametersField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceInputCreateSessionParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputCreateSessionParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputCreateSessionParams : object
    {

        private string ApplicationTypeField;

        private string ApplicationVersionField;

        private string EIDField;

        private int UserIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationType
        {
            get
            {
                return this.ApplicationTypeField;
            }
            set
            {
                this.ApplicationTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationVersion
        {
            get
            {
                return this.ApplicationVersionField;
            }
            set
            {
                this.ApplicationVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EID
        {
            get
            {
                return this.EIDField;
            }
            set
            {
                this.EIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputCreateSession", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputCreateSession : object
    {

        private AuthService.WebServiceOutputCreateSessionParams ParametersField;

        private AuthService.WebServiceStatus StatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceOutputCreateSessionParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputCreateSessionParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputCreateSessionParams : object
    {

        private string JsonWebTokenField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonWebToken
        {
            get
            {
                return this.JsonWebTokenField;
            }
            set
            {
                this.JsonWebTokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceStatus", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceStatus : object
    {

        private string CodeField;

        private string DescriptionField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputGetEndUserInfoByJsonWebToken", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputGetEndUserInfoByJsonWebToken : object
    {

        private AuthService.WebServiceInputGetEndUserInfoByJsonWebTokenParams ParametersField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceInputGetEndUserInfoByJsonWebTokenParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputGetEndUserInfoByJsonWebTokenParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputGetEndUserInfoByJsonWebTokenParams : object
    {

        private string JsonWebTokenField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonWebToken
        {
            get
            {
                return this.JsonWebTokenField;
            }
            set
            {
                this.JsonWebTokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputGetEndUserInfoByJsonWebToken", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputGetEndUserInfoByJsonWebToken : object
    {

        private AuthService.WebServiceOutputGetEndUserInfoByJsonWebTokenParams ParametersField;

        private AuthService.WebServiceStatus StatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceOutputGetEndUserInfoByJsonWebTokenParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputGetEndUserInfoByJsonWebTokenParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputGetEndUserInfoByJsonWebTokenParams : object
    {

        private AuthService.UserDepartmentList[] DepartmentListField;

        private int EIDField;

        private string FirstNameField;

        private string LastNameField;

        private string MobileNumberField;

        private int UserIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.UserDepartmentList[] DepartmentList
        {
            get
            {
                return this.DepartmentListField;
            }
            set
            {
                this.DepartmentListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EID
        {
            get
            {
                return this.EIDField;
            }
            set
            {
                this.EIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserDepartmentList", Namespace = "http://schemas.datacontract.org/2004/07/Shared.WebService")]
    public partial class UserDepartmentList : object
    {

        private System.Nullable<int> DepartmentIDField;

        private string DepartmentNameField;

        private System.Nullable<int> UnitCodeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                this.DepartmentIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                this.DepartmentNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UnitCode
        {
            get
            {
                return this.UnitCodeField;
            }
            set
            {
                this.UnitCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputReportEndUserLoginInfoByJsonWebToken", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputReportEndUserLoginInfoByJsonWebToken : object
    {

        private AuthService.WebServiceInputReportEndUserLoginInfoByJsonWebTokenParams ParametersField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceInputReportEndUserLoginInfoByJsonWebTokenParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputReportEndUserLoginInfoByJsonWebTokenParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputReportEndUserLoginInfoByJsonWebTokenParams : object
    {

        private string ApplicationTypeField;

        private string ApplicationVersionField;

        private string JsonWebTokenField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationType
        {
            get
            {
                return this.ApplicationTypeField;
            }
            set
            {
                this.ApplicationTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationVersion
        {
            get
            {
                return this.ApplicationVersionField;
            }
            set
            {
                this.ApplicationVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonWebToken
        {
            get
            {
                return this.JsonWebTokenField;
            }
            set
            {
                this.JsonWebTokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputReportEndUserLoginInfoByJsonWebToken", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputReportEndUserLoginInfoByJsonWebToken : object
    {

        private AuthService.WebServiceStatus StatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputValidateSessionByJsonWebToken", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputValidateSessionByJsonWebToken : object
    {

        private AuthService.WebServiceInputValidateSessionByJsonWebTokenParams ParametersField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceInputValidateSessionByJsonWebTokenParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceInputValidateSessionByJsonWebTokenParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceInputValidateSessionByJsonWebTokenParams : object
    {

        private string JsonWebTokenField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonWebToken
        {
            get
            {
                return this.JsonWebTokenField;
            }
            set
            {
                this.JsonWebTokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputValidateSessionByJsonWebToken", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputValidateSessionByJsonWebToken : object
    {

        private AuthService.WebServiceOutputValidateSessionByJsonWebTokenParams ParametersField;

        private AuthService.WebServiceStatus StatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceOutputValidateSessionByJsonWebTokenParams Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthService.WebServiceStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "WebServiceOutputValidateSessionByJsonWebTokenParams", Namespace = "http://schemas.datacontract.org/2004/07/MotorsazanAA")]
    public partial class WebServiceOutputValidateSessionByJsonWebTokenParams : object
    {

        private bool IsValidField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "AuthService.IApp")]
    public interface IApp
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApp/CreateSession", ReplyAction = "http://tempuri.org/IApp/CreateSessionResponse")]
        System.Threading.Tasks.Task<AuthService.WebServiceOutputCreateSession> CreateSessionAsync(AuthService.WebServiceInputCreateSession ws);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApp/GetUserInfoByJsonWebToken", ReplyAction = "http://tempuri.org/IApp/GetUserInfoByJsonWebTokenResponse")]
        System.Threading.Tasks.Task<AuthService.WebServiceOutputGetEndUserInfoByJsonWebToken> GetUserInfoByJsonWebTokenAsync(AuthService.WebServiceInputGetEndUserInfoByJsonWebToken ws);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApp/ReportUserLoginInfoByJsonWebToken", ReplyAction = "http://tempuri.org/IApp/ReportUserLoginInfoByJsonWebTokenResponse")]
        System.Threading.Tasks.Task<AuthService.WebServiceOutputReportEndUserLoginInfoByJsonWebToken> ReportUserLoginInfoByJsonWebTokenAsync(AuthService.WebServiceInputReportEndUserLoginInfoByJsonWebToken ws);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IApp/ValidateSessionByJsonWebToken", ReplyAction = "http://tempuri.org/IApp/ValidateSessionByJsonWebTokenResponse")]
        System.Threading.Tasks.Task<AuthService.WebServiceOutputValidateSessionByJsonWebToken> ValidateSessionByJsonWebTokenAsync(AuthService.WebServiceInputValidateSessionByJsonWebToken ws);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IAppChannel : AuthService.IApp, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class AppClient : System.ServiceModel.ClientBase<AuthService.IApp>, AuthService.IApp
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public AppClient() :
                base(AppClient.GetDefaultBinding(), AppClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AppClient(EndpointConfiguration endpointConfiguration) :
                base(AppClient.GetBindingForEndpoint(endpointConfiguration), AppClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AppClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(AppClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AppClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(AppClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AppClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<AuthService.WebServiceOutputCreateSession> CreateSessionAsync(AuthService.WebServiceInputCreateSession ws)
        {
            return base.Channel.CreateSessionAsync(ws);
        }

        public System.Threading.Tasks.Task<AuthService.WebServiceOutputGetEndUserInfoByJsonWebToken> GetUserInfoByJsonWebTokenAsync(AuthService.WebServiceInputGetEndUserInfoByJsonWebToken ws)
        {
            return base.Channel.GetUserInfoByJsonWebTokenAsync(ws);
        }

        public System.Threading.Tasks.Task<AuthService.WebServiceOutputReportEndUserLoginInfoByJsonWebToken> ReportUserLoginInfoByJsonWebTokenAsync(AuthService.WebServiceInputReportEndUserLoginInfoByJsonWebToken ws)
        {
            return base.Channel.ReportUserLoginInfoByJsonWebTokenAsync(ws);
        }

        public System.Threading.Tasks.Task<AuthService.WebServiceOutputValidateSessionByJsonWebToken> ValidateSessionByJsonWebTokenAsync(AuthService.WebServiceInputValidateSessionByJsonWebToken ws)
        {
            return base.Channel.ValidateSessionByJsonWebTokenAsync(ws);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://erp-server:2021/WebServices/App.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppClient.GetBindingForEndpoint(EndpointConfiguration.Soap);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppClient.GetEndpointAddress(EndpointConfiguration.Soap);
        }

        public enum EndpointConfiguration
        {

            Soap,
        }
    }
}
